// Writes resources/public/fonts.css: the Onest variable font (OFL 1.1) as
// base64 inside the stylesheet, and its licence next to it. The app serves
// only text from resources/public (routes.lg reads resources as strings), so
// a .woff2 file would not survive; a data: URL in CSS does. The version is
// pinned here; `lgx vendor-fonts` runs this.
import { writeFile } from 'node:fs/promises';

const pkg = 'https://cdn.jsdelivr.net/npm/@fontsource-variable/onest@5.3.1';
// Names are what the font is for, so the scripts people's names come in.
const subsets = ['cyrillic-ext', 'cyrillic', 'latin-ext', 'latin'];

const get = async (url, as) => {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: ${res.status}`);
  return as === 'text' ? res.text() : Buffer.from(await res.arrayBuffer());
};

// The package's stylesheet has one @font-face per subset, with the
// unicode-range that lets a browser skip the subsets a page does not use.
const css = await get(`${pkg}/index.css`, 'text');
const faces = [];
for (const subset of subsets) {
  const block = css.match(new RegExp(`/\\* onest-${subset}-wght-normal \\*/\\s*@font-face \\{[^}]*\\}`));
  if (!block) throw new Error(`no @font-face for ${subset}`);
  const range = block[0].match(/unicode-range: ([^;]+);/)[1];
  const font = await get(`${pkg}/files/onest-${subset}-wght-normal.woff2`);
  faces.push(`/* ${subset} */
@font-face {
  font-family: 'Onest';
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  src: url(data:font/woff2;base64,${font.toString('base64')}) format('woff2');
  unicode-range: ${range};
}`);
}

const header = `/* Onest, copyright 2021 The Onest Project Authors
   (https://github.com/simpals/onest), SIL Open Font License 1.1: see
   onest-OFL.txt beside this file. Generated by scripts/vendor-fonts.mjs
   from @fontsource-variable/onest 5.3.1; do not edit. */
`;
await writeFile('resources/public/fonts.css', header + faces.join('\n') + '\n');
await writeFile('resources/public/onest-OFL.txt', await get(`${pkg}/LICENSE`, 'text'));
console.log('wrote resources/public/fonts.css and onest-OFL.txt');
