// Writes the background blur into resources/public: LiveKit's track
// processors bundled into one classic script (track-processors.js, global
// LivekitTrackProcessors), MediaPipe's wasm and its loader, and the selfie
// segmentation model. By default the library fetches the wasm from jsdelivr
// and the model from Google's storage; the app serves both itself, as it
// does livekit-client, so a call page has no CDN dependency. Versions are
// pinned here; `lgx vendor-blur` runs this from the repository root.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFile, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

const PROCESSORS = '0.8.1';
const TASKS_VISION = '0.10.14'; // what @livekit/track-processors pins
const ESBUILD = '0.28.2';
// The model's URL says `latest`; the hash is the pin.
const MODEL_URL = 'https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_segmenter/float16/latest/selfie_segmenter.tflite';
const MODEL_SHA256 = '191ac9529ae506ee0beefa6b2c945a172dab9d07d1e802a290a4e4038226658b';

// The wasm and the model are served under /static/<tag>/ and cached for a
// year, so a bump must change the path. src/quickmeet/routes.lg serves
// only this tag: change both together.
const tag = `tp${PROCESSORS}-tv${TASKS_VISION}`;
const out = path.resolve('resources/public');

const work = await mkdtemp(path.join(tmpdir(), 'vendor-blur-'));
try {
  await writeFile(path.join(work, 'package.json'), '{"private": true}\n');
  execFileSync('npm', ['install', '--no-audit', '--no-fund', '--silent',
    `@livekit/track-processors@${PROCESSORS}`, `esbuild@${ESBUILD}`], { cwd: work, stdio: 'inherit' });

  const visionDir = path.join(work, 'node_modules/@mediapipe/tasks-vision');
  const { version } = JSON.parse(await readFile(path.join(visionDir, 'package.json'), 'utf8'));
  if (version !== TASKS_VISION) throw new Error(`@mediapipe/tasks-vision is ${version}, expected ${TASKS_VISION}`);

  // The package ships ES modules only. Its one runtime import from
  // livekit-client is getLogger, which the shim takes from the global the
  // page already loads. assetBase tells the page where the wasm lives.
  await writeFile(path.join(work, 'shim.js'),
    'export const getLogger = (...args) => LivekitClient.getLogger(...args);\n');
  await writeFile(path.join(work, 'entry.js'),
    `export * from '@livekit/track-processors';\nexport const assetBase = '/static/${tag}';\n`);
  const banner = `/* @livekit/track-processors ${PROCESSORS} and @mediapipe/tasks-vision ${TASKS_VISION}, ` +
    'Apache-2.0. Generated by scripts/vendor-blur.mjs; do not edit. */';
  execFileSync(path.join(work, 'node_modules/.bin/esbuild'), ['entry.js',
    '--bundle', '--minify', '--format=iife', '--global-name=LivekitTrackProcessors',
    '--alias:livekit-client=./shim.js', '--legal-comments=inline',
    `--banner:js=${banner}`, `--outfile=${path.join(out, 'track-processors.js')}`], { cwd: work, stdio: 'inherit' });

  for (const file of ['vision_wasm_internal.js', 'vision_wasm_internal.wasm']) {
    await copyFile(path.join(visionDir, 'wasm', file), path.join(out, file));
  }

  const res = await fetch(MODEL_URL);
  if (!res.ok) throw new Error(`${MODEL_URL}: ${res.status}`);
  const model = Buffer.from(await res.arrayBuffer());
  const hash = createHash('sha256').update(model).digest('hex');
  if (hash !== MODEL_SHA256) throw new Error(`selfie_segmenter.tflite is ${hash}, expected ${MODEL_SHA256}`);
  await writeFile(path.join(out, 'selfie_segmenter.tflite'), model);
} finally {
  await rm(work, { recursive: true, force: true });
}
console.log(`wrote resources/public/track-processors.js (assets under /static/${tag}),`);
console.log('vision_wasm_internal.js, vision_wasm_internal.wasm and selfie_segmenter.tflite');
